
import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(request: NextRequest) {
    try {
        const { email, results } = await request.json();

        if (!email || !results) {
            return NextResponse.json(
                { success: false, error: 'Missing email or results' },
                { status: 400 }
            );
        }

        // Create transporter using environment variables
        // If credentials are not provided, it will log to console (Mock Mode)
        const transporter = nodemailer.createTransport({
            service: 'gmail',
            auth: {
                user: process.env.EMAIL_USER,
                pass: process.env.EMAIL_PASS
            }
        });

        // Generate HTML Content
        const riskyClausesHtml = results.riskyClauses
            .filter((c: any) => c.riskLevel === 'CRITICAL' || c.riskLevel === 'HIGH')
            .map((c: any) => `
                <div style="margin-bottom: 20px; padding: 15px; border-left: 4px solid ${c.riskLevel === 'CRITICAL' ? '#ef4444' : '#f97316'}; background-color: #f9fafb;">
                    <h3 style="margin: 0 0 10px 0; color: #111827;">Clause ${c.clauseNumber} (${c.riskLevel})</h3>
                    <p style="margin: 0 0 10px 0; font-style: italic; color: #4b5563;">"${c.originalText.substring(0, 200)}..."</p>
                    <p style="margin: 0; color: #374151;"><strong>Risk:</strong> ${c.explanation.freelancer?.simple || c.explanation.company?.simple || 'Review this clause carefully.'}</p>
                </div>
            `).join('');

        const htmlContent = `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
                <div style="background-color: #1a1a1a; padding: 20px; text-align: center;">
                    <h1 style="color: #ffffff; margin: 0;">Andhakanoon Analysis</h1>
                </div>
                <div style="padding: 20px; border: 1px solid #e5e7eb;">
                    <p>Hello,</p>
                    <p>Here is the legal risk analysis for the contract: <strong>${results.document.fileName}</strong></p>
                    
                    <div style="background-color: #f3f4f6; padding: 15px; border-radius: 8px; margin: 20px 0; text-align: center;">
                        <span style="font-size: 14px; color: #6b7280; display: block; margin-bottom: 5px;">Overall Risk Score</span>
                        <span style="font-size: 32px; font-weight: bold; color: ${results.analysis.overallRiskScore >= 70 ? '#ef4444' : '#f97316'};">
                            ${results.analysis.overallRiskScore}/100
                        </span>
                    </div>

                    <h2>High Risk Clauses Found</h2>
                    ${riskyClausesHtml || '<p>No critical or high risk clauses found.</p>'}

                    <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 30px 0;" />
                    <p style="font-size: 12px; color: #9ca3af; text-align: center;">
                        Generated by Andhakanoon AI Agent.<br/>
                        This is an educational tool and not legal advice.
                    </p>
                </div>
            </div>
        `;

        if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
            console.log('--- EMAIL MOCK MODE (No Credentials) ---');
            console.log(JSON.stringify({
                recipient: email,
                subject: `Legal Analysis Report: ${results.document.fileName}`,
                riskScore: results.analysis.overallRiskScore,
                riskyClausesCount: results.riskyClauses.length,
                status: 'Simulated Sent'
            }, null, 2));
            // Simulate success in dev without credentials
            return NextResponse.json({ success: true, message: 'Mock email sent' });
        }

        await transporter.sendMail({
            from: process.env.EMAIL_USER,
            to: email,
            subject: `Legal Analysis Report: ${results.document.fileName}`,
            html: htmlContent
        });

        return NextResponse.json({ success: true });

    } catch (error) {
        console.error('Email send error:', error);
        return NextResponse.json(
            { success: false, error: 'Failed to send email' },
            { status: 500 }
        );
    }
}
